Update some of hardcoded perl.com links
tpf/perldotcom pull request #304
Opened 2021-02-01 14:04 UTC by kyzn

Hi! I found some more hardcoded perl.com links. This PR comes in two commits, one replaces two instances with relative "/" in legacy content. Other one puts hardcoded perldotcom.perl.org in places like GitHub readme and DDG search.

I've also found two "training.perl.com", but wasn't sure what to do so I left those as is.

Hope you find this useful. Do let me know if you need any updates or clarification. Thanks!

2021-02-01 15:51 UTC, briandfoy commented on content/legacy/_pub_2001_08_13_yapc-europe.md
> +Return to [Perl.com](/)
Let's just delete that line and remove the `---` above it. I made similar changes to another article last night.

2021-02-01 15:52 UTC, briandfoy commented on bin/site-is-fresh
> -my $url = 'https://www.perl.com/json/build.json';
Don't change this file. This is mostly something I use.

2021-02-01 15:58 UTC, briandfoy requested changes
A few minor adjustments and this will be good to go. Thanks!

2021-02-01 15:58 UTC, briandfoy commented on Makefile
> +SITE=https://perldotcom.perl.org
We don't need to change this one just yet. This simply supports a tool that I personally use and I already have other measures in place.

2021-02-02 12:42 UTC, kyzn commented
I've updated the PR. Removed the search part since that's already on master.

2021-02-02 16:57 UTC, briandfoy approved these changes

2021-02-02 16:57 UTC, merged

2021-02-02 16:58 UTC, briandfoy commented
Thanks for the work!