First set of files to be updated using the mcpan shortcode.
tpf/perldotcom pull request #322
Opened 2021-02-26 02:37 UTC by wpr-curly2000

Hi Brian,

As you proposed, I have updated 2 files with the mcpan shortcode:

legacy/_pub_2003_04_17_filters.md and legacy/_pub_2003_07_08_mod_perl.md

Since you cannot attach '.md' files directly.  I have appended a '.txt' to each file.  Pls let me know if there is an easier way to do attach these files.  
[_pub_2003_07_08_mod_perl.md.txt](https://github.com/tpf/perldotcom/files/6047063/_pub_2003_07_08_mod_perl.md.txt)
[_pub_2003_04_17_filters.md.txt](https://github.com/tpf/perldotcom/files/6047064/_pub_2003_04_17_filters.md.txt)

Thanks, Jeff.

2021-02-26 13:53 UTC, briandfoy commented
Thanks for doing more work. But, we need to adjust how you do this. There are 41 changed files in this PR and that's unwieldy to handle. Next time, choose one or two files at a time.

2021-02-26 14:18 UTC, briandfoy requested changes

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_1999_10_p5pdigest_THISWEEK-19991024.md
> +[Last week there was discussion of use of Unicode properties to define regex character classes](/pub/1999/10/p5pdigest/THISWEEK-19991017.html#charclasses). People interested should also consider read
This should be https://unicode.org/reports/tr18/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2000_10_p5pdigest_THISWEEK-20001030.md
> +The thread wandered off into discussion of what the Unicode characters `0x0000` and `0xFFFF` mean. Don't just guess, see the [Unicode FAQ](https://unicode.org//faq/)!
This should be https://unicode.org/faq/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2000_12_net.md
> +-   <http://web.archive.org/web/20190305142256/http://www.soaprpc.com:80/>
Turn this whole section into markdown links.

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2001_06_p5pdigest_THISWEEK-20010612.md
> +Jeff Pinyan noted that a new Java regex package contained support for the following regular expression negation: `[\w'\-[^\d]]`, which matches any word character, apostrophe, or hyphen, EXCEPT digits
This should be https://unicode.org/reports/tr18/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2001_08_p5pdigest_20010815.md
> +And while we're on the subject of Unicode, Sadahiro Tomoyuki rocks my world. Oh my. Not only has he produced an alternative and much cleaner (and more complete) module to handle normalization of Unic
This should be https://unicode.org/reports/tr10/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2001_09_26_crypto1.md
> +• <a href="http://web.archive.org/web/20061207062720/http://www.rsasecurity.com:80/rsalabs/pkcs/pkcs-3/">PKCS #3, Diffie-Hellman Key Agreement Standard</a><br />
This should be https://www.teletrust.de/fileadmin/files/oid/oid_pkcs-3v1-4.pdf

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2001_10_p5pdigest_20011021.md
> +Jarkko, apparently working all alone, has made considerable progress towards making Perl comply with "Level 1 - Basic Unicode Support", as defined by the Unicode standard, [TR\#18 "Unicode Regular Ex
This should be https://unicode.org/reports/tr18/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2001_12_19_xmlrpc.md
> +<http://web.archive.org/web/20051102170445/http://xmlrpc-c.sourceforge.net:80/xmlrpc-howto/xmlrpc-howto.html>
Turn this whole section in markdown links

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2001_12_p6pdigest_20011208.md
> +[Download](http://web.archive.org/web/20060619185554/http://www.cpan.org:80/authors/id/S/SI/SIMON/parrot-0.0.3.tar.gz) it and give it a try.
I'd change this to https://github.com/parrot/parrot

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2002_08_22_exegesis5.md
> +So let's take a look at some of those new features. To do that, we'll consider a series of examples structured around a common theme: recognizing and manipulating data in the Unix *[diff](http://web.
This should be https://www.gnu.org/software/diffutils/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2002_09_17_ewispp.md
> +    First, an image representing the graph. Second, a HTML page containing the **IMG** tag for the graph and the [imagemap](http://web.archive.org/web/20110112012108/http://www.cris.com:80/~automata/
Let's make that one https://www.w3schools.com/html/html_images_imagemap.asp

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2003_08_p6pdigest_20030803.md
> +<http://web.archive.org/web/20050816082346/http://www.hitchhiker.org:80/parrot_coverage/> -- Josh's reports
Let's make all those markdown links

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2003_08_p6pdigest_20030803.md
> +<http://web.archive.org/web/20170621155426/http://jryan.perlmonk.org/images/jirate.tar.gz>
convert to markdown links

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2004_10_21_taint_testing_kata.md
> +How do you find new ideas? One way is through [code katas](http://web.archive.org/web/20080705104855/http://pragprog.com/pragdave/Practices/CodeKata.rdoc), short pieces of code that start your learni
http://codekata.com

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2005_05_26_word_control.md
> +In a recent lightning article, [Customizing Emacs with Perl](/pub/2005/03/31/lightning2.html), [Bob DuCharme](/authors/bob-ducharme) explained how to use the Emacs `shell-command-on-region` function
https://www.gnu.org/software/emacs/manual/html_node/elisp/

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2005_07_07_navwidgets.md
> +HTML can represent these links by using `<head>` tag and `<link rel="next" href="" />`. directives. Mozilla, Firefox, and Opera all support these tags. They can be also visible in the HTML as normal
https://ftp.gnu.org/old-gnu/Manuals/make-3.80/html_node/make_toc.html

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2005_08_11_win32guitest.md
> +Another much simpler way to do this on Windows platforms is to use the free [WinSpy++](http://web.archive.org/web/20171023181503/http://www.catch22.net:80/software/winspy.asp) program. Basically, it
http://www.catch22.net/software/winspy

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2005_08_18_ical_dot.md
> +[Dot](http://www.graphviz.org/Documentation/dotguide.pdf) (PDF) is a diagramming, or directed, graph language created by Emden Gansner, Eleftherios Koutsofios, and Stephen North at Bell Labs. There a
https://gitlab.com/graphviz/webdot

2021-02-26 14:18 UTC, briandfoy commented on content/legacy/_pub_2005_10_20_scriptome.md
> +[The Scriptome](http://web.archive.org/web/20141013192711/http://sysbio.harvard.edu/csb/resources/computational/scriptome/) is a cookbook for munging biological data. The cookbook model nicely fits t
http://archive.sysbio.harvard.edu/CSB/resources/computational/scriptome/UNIX/

2021-02-26 14:18 UTC, briandfoy commented on content/promoting-perl-community-articles.md
> +{
What happened with this file that it's completely re-added?

2021-02-26 14:18 UTC, briandfoy commented on _pub_2003_04_17_filters.md
> +{
What happened with this file that it's completely re-added?

2021-02-26 14:26 UTC, briandfoy requested changes
There are so many requested changes here that I think you should abandon this pull request and start over. Make sure you're doing these things:

* `git pull` to update to the latest master (these diffs seem to be far behind)
* `git rebase` your branch
* To update a pushed branch, use `git push --force-with-lease`

Also, each commit should be one distinct change. That helps use review and cherry pick, if needed.

2021-02-26 14:31 UTC, briandfoy commented
Okay, I think I see what happened. 

Update to the latest master of this repo then make your changes for those two files. Submit a new pull request and we should just see those two files changed. When you do work again, update master first. Always update before you start work.

    git checkout master
    git pull
    git checkout -b branch_name

After you push, delete your branches. You can use the same branch name again later, but you don't want something connected to a much earlier part of the history.

    git branch -D branch_name
    git push origin :branch_name

As such, I'm closing this PR so you can redo it.

2021-02-26 14:31 UTC, closed without merging

2021-02-27 02:04 UTC, wpr-curly2000 commented
Mea Culpa Brian!

Thanks for your patience and insight!  I will get the repo updated and run the commands as you have as you have outlined.  

Thanks, Jeff.