Just a few typo corrections:)
tpf/perldotcom pull request #343
Opened 2023-05-05 01:47 UTC by jessp01

These little corrections aside, just wanted to convey how much I enjoyed reading this one:) Well done, Larry and thank you for your dedicated work over the years.

2023-05-08 19:01 UTC, briandfoy requested changes
I'll take the typo fixes, but I'd prefer to leave the formatting as is.

2023-05-08 19:01 UTC, briandfoy commented on content/legacy/_pub_2007_12_06_soto-11.md
> +Anyway, when I was a `RSTS` programmer on a PDP-11, I certainly treated BASIC as a scripting language, at least in terms of rapid prototyping and process control. I'm sure it warped my brain forever.
Undo the quoting here. Plain text is fine.

2023-05-08 19:01 UTC, briandfoy commented on content/legacy/_pub_2007_12_06_soto-11.md
> +I remember one day our computer center got a letter from Bell Labs telling us that we could get a tape of Unix V6 for cheap, only $100 because they were coming out shortly with V7. We all looked at e
Undo the quoting here.

2023-05-08 19:01 UTC, briandfoy commented on content/legacy/_pub_2007_12_06_soto-11.md
> +After several years I finally became acquainted with Unix and its various scripting languages. OK, to be more precise, `BSD`, and `csh`.
Undo the quoting here.

2023-05-10 22:58 UTC, jessp01 commented on content/legacy/_pub_2007_12_06_soto-11.md
> +Among the generalists, the conventional wisdom is that the worse-is-better approach is more adaptive. Personally, I get a little tired of the argument: My worse-is-better is better than your worse-is
I believe worser is not actually a word:) Oxford does not list it and `aspell` doesn't recognise it. Nonetheless, I've done as you've asked.

Cheers,

2023-05-11 02:06 UTC, briandfoy commented
I ended up pulling these changes into 6144387921dd4d9558c6dc0730034a56f752e455 so it would be one commit instead of a commit to undo things.

Thanks for the work,

2023-05-11 02:06 UTC, closed without merging

2023-05-11 02:33 UTC, briandfoy commented on content/legacy/_pub_2007_12_06_soto-11.md
> +Among the generalists, the conventional wisdom is that the worse-is-better approach is more adaptive. Personally, I get a little tired of the argument: My worse-is-better is better than your worse-is
Larry often uses words that aren't words.